### ISSUE TITLE
Helper mistakes a blade component for an svg

### ISSUE THREAD

**Issue by ju5t** [blade-ui-kit/blade-icons#211]
### Library version

v1.5.0

### Laravel version

v10.1.5

### PHP version

8.1.15

### Description

The svg helper mistakes a blade component for an svg.

```blade
<x-link :url="route('password.request')">
    {{ trans('auth.forgot-your-password') }}
</x-link>
```

Results in the error:

> Svg by name "link" from set "default" not found.

Our dependencies were upgraded prior to the v10 upgrade, so we were already using 1.5.0 on v9 as well.  I went through the source but couldn't find how to make sure it doesn't check for a default set. 

`blade-icons` config file does not contain a default set as per the docs. Is this still accurate?

I'm not sure what's wrong here. Any thoughts?

### Steps to reproduce

We've shift'ed (with Laravel Shift) to Laravel v10. I don't think this issue would appear in a fresh installation of Laravel, but this was the only place where I could start a discussion/issue. Sorry if this is the wrong place for it!

**Comment by driesvints** [comment]
Did you uncomment the default icon set in your config and made sure the path is pointing to the place where `link.svg` resides? 

https://github.com/blade-ui-kit/blade-icons/blob/1.x/config/blade-icons.php#L33

**Comment by ju5t** [comment]
`<x-link>` is a blade component, not an svg. Sorry if that wasn't clear from my post.

**Comment by driesvints** [comment]
I'm sorry but I don't understand your example. Can you please post all the code to reproduce this?

**Comment by ju5t** [comment]
No worries, my explanation should have been better in the first place.

I just refreshed the database and seeded it with new data and that solved the issue. I'm not sure why yet, but it somehow solved it. Sorry for bothering you about this, in the end it's probably something on our end :(

**Comment by driesvints** [comment]
No worries. Glad you got that solved 👍
