### ISSUE TITLE
Icons in subdirectories and `Unable to locate a class or view for component`

### ISSUE THREAD

**Issue by sanekb** [blade-ui-kit/blade-icons#212]
### Library version

v1.5.1

### Laravel version

v10.3.3

### PHP version

v8.1.9

### Description

it looks like the icon paths are being cached incorrectly somehow
while the command `php artisan icons:clear` does not affect what is happening

### Steps to reproduce

- do all steps from install guide

in path **resources/svg/**:
- create **nav/home.svg**
- run **localhost/** with `<x-icon-nav.home/>`, and catch `Unable to locate a class or view for component`
- delete **nav/home.svg**, create **nav.home.svg**
- reload page, and catch `Svg by name "nav.home" from set "default" not found`
- again create **nav/home.svg** _(optionally delete **nav/home.svg**)_
- reload page. it's works

part 2:
- rename subfolder to **nav2**, change component to `<x-icon-nav2.home/>`
- reload page and catch `Unable to locate...` exeption again
- fix: create **nav2.test.svg** (it could be empty file) -> reload page -> it works

**Comment by driesvints** [comment]
Did you always clear your views every time you renamed your svg's or paths?

**Comment by sanekb** [comment]
No, I haven't had to use `artisan view:clear` until now.
You're right, clearing the view cache actually leads to error `Unable to locate` after using the fix-file **nav.home.svg**

**Comment by driesvints** [comment]
Okay. I've added a note about this in the docs: https://github.com/blade-ui-kit/blade-icons/commit/6a347195d50e06eb290a29a23dea34cdc6081823

I'll try to reproduce the bug you're experiencing at a later time.

**Comment by sanekb** [comment]
Thanks, i will wait for your reply

**Comment by sanekb** [comment]
The problem can be reproduced on Windows due to different slashes in the pathnames. During the registration of icon components, the manifest is built, which is filled with names from the `format` function:
https://github.com/blade-ui-kit/blade-icons/blob/6a347195d50e06eb290a29a23dea34cdc6081823/src/IconsManifest.php#L78
```php
private function format(string $pathname, string $path): string
{
    return (string) Str::of($pathname)
        ->after($path.'/')
        ->replace('/', '.')
        ->basename('.svg');
}
```
In my case, such parameters are passed to the function (windows):
```php
'D:\blade-icons-test\resources/svg\nav\home.svg' // pathname
'D:\blade-icons-test\resources/svg' // path
'home' // format result
```
on linux:
```php
'/D/blade-icons-test/resources/svg/nav/home.svg' // pathname
'/D/blade-icons-test/resources/svg' // path
'nav.home' // format result
```

So, replacing the fixed delimiter with a constant can help correct the situation. Is this a good idea?
``` diff
 private function format(string $pathname, string $path): string
 {
+    $sep = DIRECTORY_SEPARATOR;
+
     return (string) Str::of($pathname)
-        ->after($path.'/')
-        ->replace('/', '.')
+        ->after($path.$sep)
+        ->replace($sep, '.')
         ->basename('.svg');
 }
```

**Comment by driesvints** [comment]
Thanks @sanekb. Yes I think that would solve it!

**Comment by driesvints** [comment]
I spent the entire day on it but v1.5.2 should now provide full Windows support. Let me know if you run into anything.
