### ISSUE TITLE
JavaScript code is not working for getting icon from JS - 'return <svg><use href="#icon-my-custom-hash"></use></svg>'

### ISSUE THREAD

**Issue by mahbub70** [blade-ui-kit/blade-icons#214]
### Library version

1

### Laravel version

10.10

### PHP version

8.1

### Description

Hi, I am going to work with Blade-icon. I'm successfully rendered icons in the blade template using the blade icon component. But when I am trying to get an icon from javaScript using the example code in Git Hub doc (<svg><use href="#icon-my-custom-hash"></use></svg>) it does not show anything. Here is my example code:::

     Blade Code:::
       <section hidden class="hidden">
          <x-icon name="iconsax-bro-key" defer='bro-key'></x-icon>
        </section>
  
        <section class="iconplace"></section>
 
       Javascript Code::::    
      var loadIcon = <svg><use href="#icon-bro-key"></use></svg>;
      $(".iconplace").html(loadIcon);
      console.log(loadIcon); // Given the systex error (Uncaught SyntaxError: Unexpected token '<')

      var svg = document.createElement("svg");
      var use = document.createElement("use");
      use.setAttribute("href","#icon-bro-key");
      svg.appendChild(use);
      document.querySelector(".iconplace").insertAdjacentHTML('afterbegin',svg); // Not working - [object HTMLUnknownElement]
      console.log(svg);

      var iconStore = `<svg><use href="#icon-bro-key"></use></svg>`;
      $(".iconplace").html(iconStore); // Not working - didn't show anything
      console.log(iconStore);

### Steps to reproduce

Try to load the blade icon with JavaScript by using the example code that is included with Github Doc.

**Comment by driesvints** [comment]
I'm sorry but this is beyond what support I can offer. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
