### ISSUE TITLE
Website Demo: Unable to Retrieve Icons through Search

### ISSUE THREAD

**Issue by codenashwan** [blade-ui-kit/blade-icons#225]
### Library version

1.6.0

### Laravel version

10.10

### PHP version

8.2

### Description

The current state of the website demo exhibits a malfunction in the icon search functionality. Users are encountering difficulties when attempting to search for icons, as the results are inaccurate, or the search feature fails to respond appropriately.

### Steps to reproduce

**Steps to Reproduce:**
1. Navigate to [website](https://blade-ui-kit.com/blade-icons) demo.
2. Click on the search bar.
3. Enter a search query for icons.

**Comment by driesvints** [comment]
Works for me in production?

<img width="1512" alt="Screenshot 2024-02-19 at 01 48 40" src="https://github.com/blade-ui-kit/blade-icons/assets/594614/8ea0c5bc-b8b7-4115-a071-6596c2e21c1f">
