### ISSUE TITLE
Icon search is broken on the web site

### ISSUE THREAD

**Issue by bfarrgaynor** [blade-ui-kit/blade-icons#226]
### Library version

0

### Laravel version

0

### PHP version

0

### Description

When viewing https://blade-ui-kit.com/blade-icons?set=1#search the icon search does not work. This seems to be fallout from an issue with Livewire on the site.

<img width="1428" alt="Screenshot 2024-02-18 at 9 55 12 PM" src="https://github.com/blade-ui-kit/blade-icons/assets/1213836/fdbaa680-b595-4c9d-b5d7-e14c01555e9d">

### Steps to reproduce

Visit web site in latest Safari or Chrome on OS X. (M1 Mac)

**Comment by driesvints** [comment]
Thanks. Closing in favor of https://github.com/blade-ui-kit/blade-ui-kit.com/issues/125
