### ISSUE TITLE
How to download initial svg files into the correct folder?

### ISSUE THREAD

**Issue by benlron** [blade-ui-kit/blade-icons#229]
I went through the config steps and everything seemed to work fine, but no images were downloaded to the /resources/svg folder.

What is the command that actually downloads the base images? 

The only part of the script that seemed to throw an issue is after i ran php artisan vendor:publish --tag=laravel-assets --ansi --force it returned "> @php artisan vendor:publish --tag=laravel-assets --ansi --force

   INFO  No publishable resources for tag [laravel-assets]."

Thanks. Please let me know if you need additional info

**Comment by driesvints** [comment]
There's no download. You place the icons you want to use inside this directory.
