### ISSUE TITLE
Can't use blade-uit kit icons in laravel 11

### ISSUE THREAD

**Issue by adnanerlansyah403** [blade-ui-kit/blade-icons#230]
### Library version

^3.3

### Laravel version

11

### PHP version

8.2

### Description

Can't use all icons in laravel 11

### Steps to reproduce

- Install laravel 11
- Install blade-ui kit
- Try to use the icons from blade-ui kit

**Comment by trevorgreenleaf** [comment]
@adnanerlansyah403 Just installed package and can confirm it works on Laravel 11.

**Comment by driesvints** [comment]
Thanks @trevorgreenleaf
