### ISSUE TITLE
Performacne issue

### ISSUE THREAD

**Issue by Poegim** [blade-ui-kit/blade-icons#242]
### Library version

Any (?)

### Laravel version

11

### PHP version

8.2 and 8.3

### Description

Each installation of any package ends with an increase in request time by 20-50ms per package, after installing 5-6 packages including 'heroicons, fontawesome, carbon, ...' and several others, each request increased to a minimum 250ms (application loading time in Laravel debug bar) even in views that did not render icons , including even the default login page.

### Steps to reproduce

Install Laravel 11 (Jetstream), install few packages of icons.

**Comment by driesvints** [comment]
Did you run icon caching?
