### ISSUE TITLE
  The options for the "heroicons" set don't have a prefix defined.

### ISSUE THREAD

**Issue by lewislarsen** [blade-ui-kit/blade-icons#246]
### Library version

2.4.0

### Laravel version

11.19.0

### PHP version

8.3.9

### Description

When I run my test suite, I sometimes get an intermittent error relating to the lack of registration for my heroicon UI kit.

The error is:

```
  FAILED  Tests\Unit\Models\BackupTaskTest > it does not queue up a teams notification job if a teams notification has not been set                                                                        CannotRegisterIconSet   
  The options for the "heroicons" set don't have a prefix defined.

  at vendor/blade-ui-kit/blade-icons/src/Exceptions/CannotRegisterIconSet.php:23
     19▕     }
     20▕ 
     21▕     public static function prefixNotDefined(string $set): self
     22▕     {
  ➜  23▕         return new self("The options for the \"$set\" set don't have a prefix defined.");
     24▕     }
     25▕ 
     26▕     public static function prefixNotUnique(string $set, string $collidingSet): self
     27▕     {
```

This only started happening recently, and it is very intermittent and difficult to re-produce consistently. I wanted to create an issue to make this known and to see if any other people have had a similar experience.

### Steps to reproduce

Frustratingly I can't really give a good answer here, it seems to happen more often when I run the entire test suite as opposed to targeting the one specific test it errors in.

The test itself is very basic and it doesn't interact with any front-end elements that use heroicons.

**Comment by driesvints** [comment]
Can you post your entire test please together with your composer.json and blade-icons.php config file?
