### ISSUE TITLE
Performance hit from using <x-svg (even with cache)

### ISSUE THREAD

**Issue by fruitl00p** [blade-ui-kit/blade-icons#250]
### Library version

1.7.1

### Laravel version

v11.20.0

### PHP version

8.3.2

### Description

Using the `<x-svg` as a partial inside our application incurs alot of calls to `Illuminate\View\FileViewFinder::findInPaths` (alot more than the icons used eventhough 1 icon is used multiple times)

Ive tested it using blackfire to see where the calls come from but there doesnt seem to be difference between having  `icons:cache` or without. The calls to the ViewFinder keep stacking up. Removing the `<x-svg` entirely solves the issue but leaves much to be desired ;)

I don't realy know how to reproduce in a separate repo to allow you to debug... Sorry

### Steps to reproduce

We have a 'default' icon set with custom icons in /public/svg/icons/*/*.icon.svg and build our component libary using partials and includes to allow building a `<x-button` element with an `<x-icon` and `<x-svg` inside. (but also including `<x-icon` directly incurs the calls to `findInPaths`...

**Comment by driesvints** [comment]
Hey @fruitl00p, thanks for your issue report. Could you provide a more clearer stack trace for the `findInPaths` method call so we can derive where these calls are coming from? I can then better pinpoint the issue.

**Comment by fruitl00p** [comment]
@driesvints 

I dont really know how to get a more cleaner stackstrace than this image:
<img width="1523" alt="image" src="https://github.com/user-attachments/assets/83708010-31a3-407c-854c-856a69ec1a9b">

Or i could dm the link to the profile data in Blacfire directly?

**Comment by driesvints** [comment]
And the part above it? I think that's where the Blade Icon calls originate from. Not sure.

**Comment by fruitl00p** [comment]
does this help?

<img width="887" alt="image" src="https://github.com/user-attachments/assets/43dac56a-4626-450a-bca6-1e602a415e4b">

**Comment by driesvints** [comment]
Unfortunately not.. I'm sorry but right now I don't have time to deep dive into this. Would appreciate any help figuring this one out.

**Comment by jameshulse** [comment]
I just happen to be debugging what I think is a related performance issue in our app. This is the stack trace that seems to be taking up a lot of CPU time:

![image](https://github.com/user-attachments/assets/b6587f7f-f4e4-4bbb-8c53-1cbca52e023f)

We seem to have `blade-ui-kit` installed as a sub-dependency of filament. It looks to be recursively scanning folders to build an icon manifest.

Edit: sorry, I realise I don't have the manifest cached. I will come back as to whether the cache makes a difference.

**Comment by driesvints** [comment]
@jameshulse did the caching help?

**Comment by jameshulse** [comment]
Yes I believe it did!

**Comment by driesvints** [comment]
Thanks @jameshulse.

@fruitl00p I'm very sorry but I believe I cannot help further here. I don't think there's a major issue here right now as we only have one ticket about this and the library is quite popular and widely used. Going to close this one now but if you ever figure out a way to reduce the calls I'd be happy to review a PR. Thanks
